Origen-SDK/origen_testers

- approved/v93k/flow_control.aiv
- approved/v93k/flow_control.pmfl
- approved/v93k/flow_control.tf
- approved/v93k/referenced.list
- approved/v93k/test.tf
- lib/origen_testers/smartest_based_tester/base/flow.rb
- lib/origen_testers/smartest_based_tester/base/processors.rb
- lib/origen_testers/smartest_based_tester/base/processors/empty_branch_cleaner.rb
- program/flow_control.rb
This update optimizes away cases where empty then/else branches get created (V93K-specific)
> Add empty branch cleaner for V93K flow rendering

- lib/origen_testers/igxl_based_tester/j750/test_instance.rb
Currently, utility pins are not supported when trying to use a J750 functional test, even though this is a valid thing to do in IGXL. Added support for these by adding them to the functional test hash. Names are kept the same as the other templates (bpmu, ppmu, etc).
For example,
ins.utility_pins_0 = "pin_0"
ins.utility_pins_1 = "pin_1"
will yield the following in the IGXL sheet:
> Added support for utility pins for functional test on J750 tester.

- lib/origen_testers/smartest_based_tester/base/test_method.rb
Since custom parameters are strings in 93k, having spaces is allowed as long as the custom code using those parameters deals with it. This change can handle multiple spaces in the parameter name.
> update test_method to deal with spaces in custom variable names

- lib/origen_testers/timing.rb
At the moment origen_testers is not sending the current timeset or the current timeset period to the dut.  This PR is to send the timeset period to the dut to avoid run time errors when consuming the new timing api information via wave.evaluated_events.
@ginty I was hesitant to also send the timeset name to dut.current_timeset since this will cause a fail if timeset[id] hasn't been programmed.  How can this be done safely?
> send timeset period to dut.current_timeset_period

- lib/origen_testers/igxl_based_tester/base.rb
- lib/origen_testers/smartest_based_tester/base.rb
Provide accessor for min_repeat_loop so user can change if desired.  Useful for comparing patts between testers.
> Provide access to min_repeat_loop so user can modify if desired.

- approved/v93k/prb1.tf
- approved/v93k_disable_flow/prb1.tf
- approved/v93k_enable_flow/prb1.tf
- lib/origen_testers/smartest_based_tester/base/test_suites.rb
Force name resolution to symbol (for hash key) in the make_unique method to avoid duplicate test suite names in the case where test_suite-add is done using similar string and symbol (from the flow)
Ex. From _prb1_main.rb that previously generated illegal .tf file with duplicate test suite named 'program_ckbd'.
```code
func 'program_ckbd', :tname => 'PGM_CKBD', :tnum => 1000, :bin => 100, :soft_bin => 1100
func :program_ckbd
```
> Fix unique_names bug for v93k flows

- .travis.yml
- approved/v93k/basic_interface.tf
- approved/v93k/custom_tests.tf
- approved/v93k/flow_control.tf
- approved/v93k/prb1.tf
- approved/v93k/prb2.tf
- approved/v93k/test.tf
- approved/v93k_disable_flow/prb1.tf
- approved/v93k_disable_flow/prb2.tf
- approved/v93k_enable_flow/prb1.tf
- approved/v93k_enable_flow/prb2.tf
- config/commands.rb
- lib/origen_testers/smartest_based_tester/base/flow.rb
- lib/origen_testers/smartest_based_tester/base/test_method.rb
- lib/origen_testers/smartest_based_tester/base/test_methods.rb
- lib/origen_testers/smartest_based_tester/base/test_suite.rb
- lib/origen_testers/smartest_based_tester/base/test_suites.rb
- lib/origen_testers/smartest_based_tester/v93k/templates/template.tf.erb
Added various sorting helper methods to mimic how Smartest exports the tf file on 'Save'.  Tested with several different test flows.  However, I'm certain there are still some corner cases not covered that will generate different spacing and possible ordering, but this PR should clean up most diff issues.
> Polished the tf output to be a closer match to Smartest export

- approved/v93k/flow_control.tf
- lib/origen_testers/smartest_based_tester/base/flow.rb
- lib/origen_testers/smartest_based_tester/base/generator.rb
- program/flow_control.rb
Enables the user to pass a flow_name: option on the top-level Flow.create line which specifies the name of the top-level group in the output file.  Without flow_name: specified, the behavior defaults to the current: filename.upcase.
> Custom v93k flow name

- lib/origen_testers/smartest_based_tester/base/test_suite.rb
- spec/v93k_unique_test_names_spec.rb
Added the ability to prepend flowname or strings to each test:
- :pre_flow_name or :preflowname will put the flow name at the beginning of each test
- :prepend_somestring will add somestring to the beginning of each test
- :append_somestring behaves the same as :somestring
> Enhanced the unique test name generator 

- lib/origen_testers/timing.rb
- spec/pattern_compilers_spec.rb
- spec/timing_spec.rb
Due to the way this _if_dut method was originally implemented and used it meant that the code to update the DUT timeset was never triggered.
Added a test to catch it and the appropriate fix.
> Fixed bug in set_timeset method

- lib/origen_testers/smartest_based_tester/base/test_method.rb
Made a mistake in my last commit, the function smt8? was not in scope, changed it to tester.smt8?
> Changed smt? to tester.smt?

- lib/origen_testers/smartest_based_tester/base/test_method.rb
- lib/origen_testers/smartest_based_tester/base/test_methods/limits.rb
This PR allows a test interface to pass a test method parameter :limits_id and set the limits ID in the .tf file.  If it is not passed, the previous behavior is used.  This [issue](https://github.com/Origen-SDK/origen/issues/251) is the basis for the PR.
> fix for origen issue 251

- approved/generic_overlay_capture/v93k/test_overlay.avc
- approved/generic_overlay_capture/v93k/test_overlay_part1.avc
- lib/origen_testers/smartest_based_tester/base.rb
- pattern/tester_overlay.rb
Adds a new overlay_style called :handshake and has an implementation of it on V93K.
In principle it is designed for when you want to implement the overlay using vectors generated in the ATE language, e.g. SmartVec/RDI on the 93K.
So whenever such an overlay is encountered, the overlay vectors are inhibited in the same as they are with the existing subroutine style of overlay, but instead of calling a subroutine it instead does a handshake with the tester.
That is implemented by simply calling the existing handshake API, which for the 93K will split the pattern at that point.
A doc update for it is in this PR - https://github.com/Origen-SDK/origen/pull/268
> Added handshake overlay style and v93k implementation

- lib/origen_testers/vector_pipeline.rb
When tester.vector_group_size is > 1 and the "-v" generate option is used, the inline cycle comment was incorrect. This fixes it. But, I couldn't figure out a way to explicitly test it. Any test suggestions?
> correct verbose inline vector comments with group_size > 1

- lib/origen_testers/pattern_compilers/base.rb
Fixes a pattern compiler crash in the case that the pattern compiler object is being created before the actual app.config.output_directory has been created.  This patch will create the output_directory if necessary.
> Create output_directory for pattern_compiler if necessary

- lib/origen_testers/smartest_based_tester/base/flow.rb
~~~ruby
Flow.create interface: 'MyInterface' do
flow.flow_name = 'SETUP'
flow.flow_description = 'Setup Variables and Guardbands'
test :setup_test, cont: true
end
~~~
renders;
~~~
-----------------------------------------------------------------
test_flow
{
run(setup_test);
}, open,"SETUP","Set Variables and Guardbands"
end
-----------------------------------------------------------------
~~~
> Add support for flow description for 93K

- lib/origen_testers/pattern_compilers/v93k.rb
I ran into a problem where the V93K pattern compiler option crashed in a particular environment, I believe because the default/native file format was not UTF-8.
Anyway, this patch fixes it.
> Fix encoding issue

- lib/origen_testers/smartest_based_tester/base/test_method.rb
- templates/origen_guides/program/v93k.md.erb
This allows custom test method definitions for the V93K (SMT7) to declare attributes as boolean type and then assign them true/false and they will be rendered as a 1/0 integer.
This update has been on the SMT8 branch for a long time, but bringing it over to the mainline since its usage has crept into origen_std_lib.
> Added support for boolean types in V93K test method attributes

- lib/origen_testers/pattern_compilers/v93k/digcap.rb
Minor update to permit skipping digcap setup in AIV for v93k.
> Added option to skip digcap AIV setup.

- lib/origen_testers/pattern_compilers/v93k.rb
Issue #145:
The avc_digcap_vpf method in lib/origen_testers/pattern_compilers/v93k.rb increments the capture_vectors variable by one for each appearance of the digcap.capture_string string. This does not take into account of vector looping which is used in the MTR bitmapping patterns
> The avc_digcap_vpf method does not handle looping correctly #145

- approved/generic_overlay_capture/ultraflex/test_overlay_no_start.atp
- examples/pattern_generator.rb
- lib/origen_testers/igxl_based_tester/base.rb
- pattern/tester_overlay_no_start.rb
- templates/origen_guides/pattern/ultraflex.md.erb
There are a few rare scenarios when you don't want Origen to automatically insert the digsrc instrument start command. This PR provides a way to turn it off.
> Skip dig src start

- lib/origen_testers/smartest_based_tester/base/variables_file.rb
- lib/origen_testers/smartest_based_tester/v93k/templates/vars.tf.erb
I threw together a quick and simple testcase for some unrelated dev work, but ran into an error. I found that if no variables were created by the flow then the origen p command would error out. 
This PR allows for program generation to complete when no system or user variables are generated for the v93k
> allow for program generation when no variables were created

- lib/origen_testers/labview_based_tester/pxie6570.rb
In the case where a pattern is created but no cycles are generated, the header method would hang. Not something you'd normally expect to be done. But, in the case where you're taking advantage of the 64 cycle minimum cycle count, you can still get a valid pattern without ever generating a cycle.
> fixed a corner case bug that causes the generator to hang

- approved/j750/flow_control_flag_bug_flow.txt
- approved/j750_hpt/flow_control_flag_bug_flow.txt
- approved/ultraflex/Jobs.txt
- approved/ultraflex/flow_control_flag_bug_flow.txt
- approved/v93k/testflow/mfh.testflow.group/flow_control_flag_bug.tf
- approved/v93k_smt8/OrigenTesters/flows/FLOW_CONTROL_FLAG_BUG.flow
- approved/v93k_smt8/OrigenTesters/limits/Main.FLOW_CONTROL_FLAG_BUG_Tests.csv
- lib/origen_testers/igxl_based_tester/base/flow.rb
- program/flow_control_flag_bug.rb
- program/prod.list
I was unable to create a case to duplicate the error. But, there is a case where the object passed to <code>clean_flag</code> is frozen (immutable). The string created by <code>to_s</code> will also be frozen in that case. The <code>.dup</code> method returns a mutable copy of the string.
> get unfrozen string before modifying

- lib/origen_testers/api.rb
- lib/origen_testers/smartest_based_tester/base.rb
- program/prb1.rb
C or Java code program comment char not set properly for SMT7/8 test programs.  Since was not set would default to `#` which would make having built-in Origen diffs not be able to skip those comments in that code.
Have added `program_comment_char` for Smartest_based testers.
Also added ability for user to modify the `comment_char`or `program_comment_char` for any tester -- in case a strange case comes up in the future.
> ADD program comment chars for SMT7/8

- .github/workflows/regression_tests.yml
- lib/origen_testers/igxl_based_tester/decompiler.rb
- lib/origen_testers/igxl_based_tester/decompiler/atp.rb
This update is to handle the case where the pin list isn't on the same line as the vector key word (this is how Origen creates UltraFlex patterns).
> more reliable pinlist start detection

- lib/origen_testers/decompiler/nodes.rb
The reverse compiler (from a binary pattern file back to an ASCII pattern file) adds extra spaces to the pin list. The origen decompiler was turning that into a list of pins with a lot of spaces in their names (which don't exist in the app).
> remove extra spaces before converting to symbol

- .github/workflows/regression_tests.yml
- approved/stil/v93k_workout.stil
- lib/origen_testers/stil_based_tester/base.rb
Previously if a pin group was listed in the pin_pattern_order statement it was treated as though it was a single pin in the signal definition and timing definition sections of the output STIL. This PR is to include all of the pins from the group (see the 1 approved output change for an example).
> Stil groups

- lib/origen_testers/atp/flow.rb
- origen_testers.gemspec
- spec/atp/loop_spec.rb
Revert to Ruby loop keyword functionality if only block is given with no args, otherwise treat as testflow loop api.
> Allow Ruby loop keyword within flow

- lib/origen_testers/smartest_based_tester/base.rb
- lib/origen_testers/smartest_based_tester/base/flow.rb
This is an update to the commit on 10/6/2023.  We need to keep the existing behavior that is no insertion in the flow path.
Add in an option to add the insertion.  In the environment/v93k_smt8.rb
add insertion_in_the_flow_path: true
> add option to add insertion in the flow path

- approved/v93k/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_disable_flow/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_enable_flow/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_flowgrouping/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- approved/v93k_flowgrouping/OrigenTesters/limits/Main.PRB1_Tests.csv
- approved/v93k_global/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_multiport/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_smt8/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- approved/v93k_smt8/OrigenTesters/limits/Main.PRB1_Tests.csv
- lib/origen_testers/smartest_based_tester/base/test_method.rb
- lib/origen_testers/test/interface.rb
- program/components/_prb1_main.rb
SMT8 requires the types to be maintained for the parameters. Without forcing the type in the parameters, providing a string to integers and doubles will show up as strings in the final output.
> Force integer and double to their respective types

- lib/origen_testers/atp/flow_api.rb
Update flow_api wrapper method of flow.loop to **handle case where interface has not been created yet**
> Ruby Flow keyword patch

- approved/v93k_flowgrouping/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- approved/v93k_smt8/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- lib/origen_testers/atp/flow.rb
- lib/origen_testers/atp/flow_api.rb
- lib/origen_testers/smartest_based_tester/v93k_smt8/test_suite.rb
- lib/origen_testers/test/interface.rb
The alias handling for nested parameters was not matching the other core locations. I had to update here to align with expected key handling.
> Fix the period alias on nested parameters

- Gemfile
- lib/origen_testers/decompiler/nodes.rb
- lib/origen_testers/igxl_based_tester/decompiler/atp.rb
Various bug fixes for issues uncovered while running origen convert on ascii patterns from various sources:
1) End of line comments that origen creates when generating with -v option cause the vector to be detected as a label
2) Trailing ":S" on pin names needs to be removed (ex: JTAG:S, CLKS:S, etc.)
3) Blank lines cause a run time error
> Convert updates

- approved/v93k_flowgrouping/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- approved/v93k_flowgrouping/OrigenTesters/limits/Main.PRB1_Tests.csv
- approved/v93k_smt8/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- approved/v93k_smt8/OrigenTesters/limits/Main.PRB1_Tests.csv
- lib/origen_testers/smartest_based_tester/base/flow.rb
- lib/origen_testers/smartest_based_tester/v93k_smt8/flow.rb
- lib/origen_testers/smartest_based_tester/v93k_smt8/generator.rb
- lib/origen_testers/smartest_based_tester/v93k_smt8/shmoo_test.rb
- lib/origen_testers/smartest_based_tester/v93k_smt8/shmoo_tests.rb
- lib/origen_testers/smartest_based_tester/v93k_smt8/templates/template.flow.erb
- lib/origen_testers/test/interface.rb
- program/components/_prb1_main.rb
- templates/origen_guides/program/v93ksmt8.md.erb
Implements native shmoo testflow element in SMT8 as describe in TDC Topic 253309.
**Example interface:**
```
def shmoo(name, targets, options = {})
if tester.v93k? && tester.smt8?
targets = [targets] unless targets.is_a?(Array)
st = shmoo_tests.run(name, { targets: targets }.merge(options))
flow.test st, options
end
end
```
**Example flow:**
```
Flow.create
...
test :cc_test_0, options
...
range = { start: 3.0, stop: 5.0, steps: 10 }
axis = { name: :axis1, resource_type: 'specVariable', resource_name: 'vcc', range: range }
shmoo :shmoo_over_ts_1D, :cc_test_0, title: 'shmooOverTest', execution_order: :horizontal, axis: axis
...
end
```
**Renders:**	  
```
flow <FLOW> {
setup {
shmoo shmoo_over_ts_1D {
target = cc_test_0;
resultTitle = "shmooOverTest";
executionOrder = horizontal;
axis …
```
> SMT8 built-in shmoo element

- approved/v93k/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_disable_flow/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_enable_flow/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_flowgrouping/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- approved/v93k_global/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_multiport/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_smt8/OrigenTesters/flows/prb1/PRB1_MAIN.flow
- lib/origen_testers/smartest_based_tester/base/test_method.rb
- lib/origen_testers/test/interface.rb
Resolves SMT8 bug introduced in #222 where parameter of empty string will render as empty string (which is what we want on SMT7) which causes flow to not compile due to type mismatch.
Adds proper test cases for both SMT7 and SMT8.
> Patch for rendering empty default TM parameters on SMT8

- lib/origen_testers/charz.rb
- lib/origen_testers/charz/profile.rb
- templates/origen_guides/program/charz.md.erb
An oversight in the original charz API code I wrote, adding new placements would require each profile to also specify that they're also valid. Now you can use an interface instance variable to notify all profiles of valid placements.
Also added a guide on how to create custom placements as it wasn't obvious if you're not familiar with the API already.
> Simplified adding new charz placements globally

- approved/j750/prb1_flow.txt
- approved/j750_hpt/prb1_flow.txt
- approved/ultraflex/prb1_flow.txt
- approved/v93k/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_disable_flow/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_enable_flow/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_flowgrouping/OrigenTesters/flows/PRB1.flow
- approved/v93k_flowgrouping/OrigenTesters/flows/prb1/DEFAULT_NO_GROUP_IMPORT.flow
- approved/v93k_flowgrouping/OrigenTesters/limits/Main.PRB1_Tests.csv
- approved/v93k_global/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_multiport/testflow/mfh.testflow.group/prb1.tf
- approved/v93k_smt8/OrigenTesters/flows/PRB1.flow
- approved/v93k_smt8/OrigenTesters/flows/prb1/DEFAULT_NO_GROUP_IMPORT.flow
- approved/v93k_smt8/OrigenTesters/limits/Main.PRB1_Tests.csv
- lib/origen_testers/generator.rb
- lib/origen_testers/origen_ext/generator/flow.rb
- program/components/_default_group_import.rb
- program/components/_default_no_group_import.rb
- program/prb1.rb
- templates/origen_guides/program/v93ksmt7.md.erb
- templates/origen_guides/program/v93ksmt8.md.erb
We have some complex flows that benefit from an aggressive use of sub flows, which are looped over and call then call further sub flows, etc.
For V93k this can lead to a degraded user experience on the tester by having to dig through many nested groups to find the tests, or worse on smt8 a program that should reasonably have a dozen .flow files at most can end up with a couple hundred files to manage.
This gives the user the ability to opt out of that group creation on sub flow import.
Additionally, I have a use case that being able to interact with the flow options passed to the import statement just before Flow.create's block was processed was useful, so its now stored in the Flow.create's options so that startup and shutdown hooks have it available.
Lastly, I have yet another use case …
> v93k7/8 can disable subflow import grouping; enhanced startup/shutdown with flow options
